# Site settings
title: Never Cinderella
email: raphaelle@nevercinderella.com
description: Let's talk about fashion and life in the 21st Century.
baseurl: ""
url: "http://nevercinderella.com"

# Build settings
markdown: kramdown
permalink: pretty
gems:
  - jekyll-sitemap